apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-seed
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: yah3i94/testapp:app
          command: ["node", "seeds/seed.js"]
          env:
            - name: DB_HOST
              value: "mongodb://mongod-svc:27017/posts"
