apiVersion: v1
kind: Service
metadata:
  name: testapp-svc
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
    - port: 3000 # Port exposed by the service
      targetPort: 3000 # Port on the container
      nodePort: 30001 # External port on the node
      protocol: TCP
