apiVersion: v1
kind: Service
metadata:
  name: mongod-svc
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017 # Port exposed by the service
      targetPort: 27017 # Port on the container
      protocol: TCP
