---
- name: Install Nginx Play
  hosts: web
  gather_facts: yes
  become: yes # Allows privilege escalation (like sudo)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install and start Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
